'use strict';
/** C08: seed the bundled sample project locally. No provider is contacted; media is generated by script. */
const fs = require('fs');
const path = require('path');
const dramaService = require('./dramaService');
const storyboardService = require('./storyboardService');
const { SAMPLE_ID, sample } = require('../sample/story');
const { makeImagePng, makeWav } = require('../sample/assets');

function parseMeta(raw) {
  try { return raw ? JSON.parse(raw) : {}; } catch (_) { return {}; }
}

/** Existing, non-deleted sample drama row or null. */
function findSeeded(db) {
  const rows = db.prepare('SELECT id, metadata FROM dramas WHERE deleted_at IS NULL AND metadata LIKE ?').all(`%${SAMPLE_ID}%`);
  for (const r of rows) {
    if (parseMeta(r.metadata).sample_id === SAMPLE_ID) return r;
  }
  return null;
}

function listSamples(db) {
  return [{ id: SAMPLE_ID, title: sample.title, description: sample.description, shots: sample.shots.length, seeded: !!findSeeded(db) }];
}

function firstEpisodeId(db, dramaId) {
  const ep = db.prepare('SELECT id FROM episodes WHERE drama_id = ? AND deleted_at IS NULL ORDER BY episode_number, id').get(dramaId);
  return ep ? ep.id : 0;
}

/**
 * Create the sample drama (idempotent: a second call returns the existing one).
 * @returns {Promise<{drama_id:number, episode_id:number, created:boolean}>}
 */
async function seedSample(db, log, storageRoot, sampleId = SAMPLE_ID) {
  if (sampleId !== SAMPLE_ID) { const e = new Error('示例不存在'); e.status = 404; throw e; }
  const existing = findSeeded(db);
  if (existing) return { drama_id: existing.id, episode_id: firstEpisodeId(db, existing.id), created: false };

  const relDir = path.posix.join('projects', 'sample', SAMPLE_ID);
  const absDir = path.join(storageRoot, ...relDir.split('/'));
  fs.mkdirSync(absDir, { recursive: true });
  // Media first, so a failure leaves no half-seeded rows.
  const files = [];
  for (let i = 0; i < sample.shots.length; i++) {
    const s = sample.shots[i];
    const img = `shot-${i + 1}.png`;
    fs.writeFileSync(path.join(absDir, img), await makeImagePng({ hue: s.hue, discY: 0.22 + (i % 3) * 0.08 }));
    let wav = null;
    if (s.narration || s.dialogue) {
      wav = `shot-${i + 1}.wav`;
      fs.writeFileSync(path.join(absDir, wav), makeWav({ freq: s.freq, seconds: Math.min(s.duration - 0.5, 2) }));
    }
    files.push({ img: `${relDir}/${img}`, wav: wav ? `${relDir}/${wav}` : null });
  }

  const total = sample.shots.reduce((a, s) => a + s.duration, 0);
  const run = db.transaction(() => {
    const drama = dramaService.createDrama(db, log, {
      title: sample.title,
      description: sample.description,
      genre: sample.genre,
      style: sample.style,
      metadata: {
        sample_id: SAMPLE_ID,
        aspect_ratio: sample.aspectRatio,
        template_id: sample.genre,
        target_duration_sec: Math.round(total),
        story: sample.story,
        characters: sample.characters,
        scenes: sample.locations.map((n) => ({ name: n })),
      },
    });
    const now = new Date().toISOString();
    const ep = db.prepare(
      `INSERT INTO episodes (drama_id, episode_number, title, script_content, description, duration, status, created_at, updated_at) VALUES (?, 1, ?, ?, ?, ?, 'draft', ?, ?)`
    ).run(drama.id, sample.title, sample.story, sample.description, Math.round(total), now, now);
    const episodeId = Number(ep.lastInsertRowid);
    for (const c of sample.characters) {
      db.prepare('INSERT INTO characters (drama_id, name, role, description, appearance, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?)')
        .run(drama.id, c.name, c.role, c.description, c.appearance, now, now);
    }
    sample.shots.forEach((s, i) => {
      const sb = storyboardService.createStoryboard(db, log, {
        episode_id: episodeId,
        storyboard_number: i + 1,
        title: s.location,
        description: s.visual,
        location: s.location,
        duration: s.duration,
        dialogue: s.dialogue,
        image_prompt: s.visual,
        video_prompt: s.visual,
      });
      storyboardService.updateStoryboard(db, log, sb.id, {
        shot_type: s.camera,
        narration: s.narration,
        local_path: files[i].img,
        narration_audio_local_path: files[i].wav,
        status: 'completed',
      });
    });
    return { drama_id: Number(drama.id), episode_id: episodeId, created: true };
  });
  return run();
}

module.exports = { listSamples, seedSample, findSeeded };
